#!/bin/sh
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Modifications by Carlos Neves <carlos@neves.me>

interface='wlan0'

# As per #36 -- It is transparent: e.g. if the machine has no
# battery or wireless connection (think desktop), this block
# should not be displayed.
if ! test -d /sys/class/net/$interface/wireless; then
  exit 0
fi

# If the wifi interface exists but no connection is active,
# "down" shall be displayed.
if test "$(cat /sys/class/net/$interface/operstate)" == 'down'; then
  echo ' <span color="#ffffff">睊</span> '
  exit 33 # make background #ff0000
fi

state='short'
while true; do
  quality=$(grep $interface /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
  quality_float=".$(echo $quality | cut -d'.' -f1 | sed 's/0$//')"

  if test "$quality" == '100'; then
    quality_float='<span size="small"> </span>1'
  fi

  if test "$state" == 'short'; then
    color='#ffffff'
    echo " <span color='$color'><span font='Hack Nerd Font'>直</span>$quality_float</span> "
  else
    if test "$quality" -ge '80'; then
      color='#00ffff'
    elif test "$quality" -ge '60'; then
      color='#00aaaa'
    elif test "$quality" -ge '40'; then
      color='#006666'
    else
      color='#002222'
    fi
    essid=$(iwctl station wlan0 show | grep 'Connected network' | xargs echo | cut -d' ' -f3-)
    ipv4=$(ip addr show wlan0 | grep -oE '^[ ]*inet [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | grep -oE '[^a-z ]+')
    echo " <span color='$color'><span font='Hack Nerd Font'>直</span>$quality_float \"$essid\" $ipv4</span> "
  fi

  read -t .9 button
  if test "$button" == '1'; then
    if test "$state" == 'short'; then
      state='full'
    else
      state='short'
    fi
  fi
done
